import colorsys
## generated by ChatGPT ##
def gen_colors(n):
    colors = []
    for i in range(n):
        # Generate hue values spaced evenly around the color wheel
        hue = i / n
        # Set saturation and value to 1 for vibrant colors
        saturation = 1
        value = 1
        # Convert HSV to RGB and append to colors list
        color = colorsys.hsv_to_rgb(hue, saturation, value)
        colors.append(color)
    return colors